baseURL = 'https://evan-luan.github.io/'
title = 'Whispers in the Void'
theme = "hermit-v2"
languageCode = "en-us"
pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "Evan Luan"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  name = "Evan Luan"
  bio = "Just a lonely ranter blogging about stuff."

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

[params]
  # description = "CHANGE ME SITE DESCRIPTION"
  # images = [""]
  themeColor = "#494f5c"
  accentColor = "#018472"

  #homeSubtitle = "CHANGE ME HOME SUBTITLE"
  footerCopyright = "CHANGE ME FOOTER COPYRIGHT"
  # footerHideThemeName = false
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # listLayout = ["description","tags","categories","legacy"]
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true
  # mathjaxLib = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
  # mermaidLib = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"
  [params.gallery]
    enable = true
    thumbnail = '300'

  [params.dateform]
    LongDate = "Jan 2, 2006"
    ShortDate = "Jan 2"
    NumDateShort = "2006-01-02"
    NumDateLong = "2006-01-02 15:04 -0700"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/evan-luan"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20